version: "3.3"
services:
  master: 
    image: dvemuri/dist_fog_comp:pi-akka-cluster
    ports:
      - "2550:2550"
    environment:
      CLUSTER_PORT: 2550
      CLUSTER_IP: master
      SEED1_IP: worker1
      SEED2_IP: worker2
      
      ROLE: master
    deploy:
      replicas: 1      
      placement:
        constraints: [node.role == manager]
    command: ["java","-jar","/app.jar", "master", "2550"]

  worker1: 
    image: dvemuri/dist_fog_comp:pi-akka-cluster-rasp
    ports:
      - "2552:2552"
    
    environment:
      CLUSTER_PORT: 2552
      CLUSTER_IP: worker1
      SEED1_IP: worker1
      SEED2_IP: worker2
      
      ROLE: worker
    deploy:
      replicas: 1      
      placement:
        constraints: [node.role == worker]
    command: ["java","-jar","app.jar", "worker", "2552"]

  worker2: 
    image: dvemuri/dist_fog_comp:pi-akka-cluster
    ports:
      - "2534:2534"
    environment:
      CLUSTER_PORT: 2534
      CLUSTER_IP: worker2
      SEED1_IP: worker1
      SEED2_IP: worker2
      
      ROLE: worker
    deploy:
      replicas: 1      
      placement:
        constraints: [node.role == manager]
    command: ["java","-jar","/app.jar", "worker", "2534"]
